messages:
   noper: '&cУ вас нет прав!'
   messages: '&aУ %name% на канале, сейчас стрим: %url%'
   successfully: '&aУспешно сохранено!'
   stopstream: '&a%name% закончил стримить на сервере!'
   nostream: '&cВы неможете остановить стрим если вы не стримите!'